---
title: "R Notebook for FD"
output:
  html_document:
    df_print: paged
---


```{r}
library(readxl)
df=read_excel("C:\\Users\\DELL\\OneDrive\\Desktop\\SurveyDataUpdated.xlsx",sheet=1)
head(df,10)

```



```{r}
library(tidyverse)
library(flextable)

```


```{r}
sum(is.na(df))
na.omit(df)
df1=as.data.frame(df)
```


```{r}
sum(is.na(df1$farm_income))
sum(is.na(df1$total_family_members))
sum(is.na(df1$otherincome))
sum(is.na(df1$water_sources))

```



```{r}
with(df1,table(family_type,education))
table(df1$religion)
table(df1$lack_of_processing_units)
table(df1$low_market_price)
table(df1$tractor_scheme)
table(df1$rupee_insurance)
table(df1$overdue_loan)
table(df1$pan_card)
table(df1$irrigation_problem)
table(df1$financial_stress_1)
table(df1$suicidal_ideation_1)
table(df1$`income_sources/agriculture`)
table(df$loan_amount)
table(df1$education)
```


```{r}
library(lattice)
df2=df1 |> mutate(religion=recode(religion,"हिंदू"="Hindu","हिन्दु"="Hindu","हिंदुं"="Hindu","हिंदु"="Hindu"))   |>
         mutate(subcaste=recode(subcaste,"ओ बी सी"="OBC","ओ . बी .सी."="OBC","ओ.बी.सी."="OBC","ओ.बी.सी"="OBC","ओ .बी सी ."="OBC","ओ .बी .सी"="OBC","ओ .बी .सी"="OBC","इतर मागासवर्गीय"="OBC","अनुसूचित जमाती  ST"="ST","Dhangar NTC"="NT-C","Obc"="OBC","ओबीसी"="OBC"
))
```

```{r}
literacy_of_deceased=c('graduate', 'higher_secondary', 'illiterate'  , ' primary', 'secondary' )
Counts=c(13,36,28,79,73)
colors=c('#ffb997','#621940','#fbb521','lightblue','#f67e7d')
par(bg='wheat1')
percentag=round(Counts/sum(Counts)*100,2)
pie(Counts,labels = paste(percentag,"%"),col=colors,radius=1,border='white',main='Literacy',cex=1.3)
#pie(Counts,labels=literacy_of_deceased,col=colors,main='Literacy ',cex=1.3)

radius <- 0.4  # Adjust the size of the hollow area
symbols(0, 0, circles = radius, add = TRUE, inches = FALSE, bg = "wheat1", fg = "black")
legend('topleft',legend=literacy_of_deceased,fill=colors,cex=1,x=-2.5,y=1.1)

```


```{r}

Amount_To_Pay=c('1lakh_5lakh','50k_75k','75k_1lakh','above_5lakh','below_50k')
Status=c(16,4,1,8,3)
bar_colors <- c('#b3e5fc', '#4fc3f7', '#0288d1', '#fbc02d', '#ff7043')
par(bg='white',col.axis='black',col.lab='black',col.main='navy')
bp=barplot(names.arg=Amount_To_Pay,height=Status,col=bar_colors,main='Loan Amount to Pay')

percentages=round(Status/sum(Status)*100,1)
text(bp,Status/2,labels=paste(percentages,"%"),cex=1.3,col='navy')                      # cex for font size
mtext("Amount_To_Pay", side = 1, line = 3, col = "navy", font = 2)  # X-axis label
mtext("Counts ( not in %)", side = 2, line = 3, col = "navy", font = 2) 
grid(nx=NA,ny=NULL,col = 'navy',lty=2,lwd=0.7)
```


```{r}

Suicidal_Ideation=c('always','never','often','rarely')
Status=c(5,9,13,9)
bar_colors=c('red','red3','red4','#f67e7d')
par(bg='black',col.axis='white',col.lab='white',col.main='red1')
percentages=round(Status/sum(Status)*100,1)
bp1=barplot(names.arg=Suicidal_Ideation,height=Status,col=bar_colors,main='Suicidal Ideation among Family Members of Deceased farmer')
text(bp1,Status/2,labels=paste(percentages,"%"),cex=1.3,col='black')
mtext("Suicidal_Ideation", side = 1, line = 3, col = "red1", font = 2)  # X-axis label
mtext("Counts (not in %)", side = 2, line = 3, col = "red1", font = 2) 
grid(nx=NA,ny=NULL,col = 'white',lty=2,lwd=1.2)
```



```{r}

Tractor_Scheme=c('applied_no_benefit','aware_not_applied','no_documents','no_info',' received_benefit')
Status=c(1, 10,1,23,1 )
bar_colors=c('green4','green3','green2','green1','green')
par(bg='black',col.axis='white',col.lab='white',col.main='green')
bp2=barplot(names.arg=Tractor_Scheme,height=Status,col=bar_colors,main='Beneficiary of Tractor Schemes',xlab='')
percentages=round(Status/sum(Status)*100,1)
text(bp2,Status/2,labels=paste(percentages,"%"),cex=1.3,col='white')
mtext("Tractor_Scheme", side = 1, line = 3, col = "green", font = 2)  # X-axis label
mtext("Counts", side = 2, line = 3, col = "green", font = 2) 
grid(nx=NA,ny=NULL,col='white',lwd=1.1,lty=2)
```



```{r}
table(df1$`water_sources/none`)
Water_source_availability=c('Yes','No')
Counts=c(107,122)
Proportion=round(Counts/sum(Counts)*100,2)
par(bg='beige',col.main='blue')
pie(Counts,labels=paste(Proportion,'%'),col=c('blue2','tan'),radius=1.1,border='black',main='Water Source Availability Ratio',cex=1.2)
symbols(0,0,circles=0.3,bg='wheat',add=TRUE)
legend('topleft',legend=Water_source_availability,fill=c('blue2','tan'),cex=1.1,bg='wheat2',x=0-0.32,y=0.2)
```

```{r}
table(df1$no_compensation)
Reviwes_regarding_compension=c('agree','disagree','neutral','strongly_agree','strongly_disagree')
Status=c(67,28,41,90,3)
bar_colors <- c('#b3e5fc', '#4fc3f7', '#0288d1', '#fbc02d', '#ff7043')
par(bg='tan',col.axis='black',col.lab='black',col.main='navy')
bp=barplot(names.arg=Reviwes_regarding_compension,height=Status,col=bar_colors,main='Reviwes of Family in regards with no compension provided')

percentages=round(Status/sum(Status)*100,1)
text(bp,Status/1.7,labels=paste(percentages,"%"),cex=1.3,col='navy')                      # cex for font size
mtext("Reviwes", side = 1, line = 3, col = "navy", font = 2)  # X-axis label
mtext("Counts ( in numbers)", side = 2, line = 3, col = "navy", font = 2) 
#grid(nx=NA,ny=NULL,col = 'navy',lty=2,lwd=0.7)
```


```{r}
df1$kisan_credit <- ifelse(is.na(df1$kisan_credit), "Unknown", df1$kisan_credit)
df$`income_sources/agriculture` <- ifelse(is.na(df$`income_sources/agriculture`), "Unknown", df$`income_sources/agriculture`)

tb=table(df1$kisan_credit,df$`income_sources/agriculture`)
library(vcd)

```




```{r}
table(df1$ration_card)
Ration_Card_Status=c('none','orange','white','yellow')
colors=c('tomato','darkorange','white','#fbb521')
count=c(4,125,4,96)
par(bg='#E2D8A5') 
percentag=round(count/sum(count)*100,2)
pie(count,labels = paste(percentag,"%"),col=colors,radius=1,border='white',main='Ration Card Distribution Among the Families',cex=1.3)
symbols(0,0,circles=0.5,add=TRUE,inches=FALSE,bg='wheat1')
legend('topleft',legend=Ration_Card_Status,fill=colors,bg='wheat',x=-2.4,y=1,cex=1.1)

```



```{r}
table(df1$water_sources,df1$irrigation_problem)

```



```{r}
table(df1$taluka)
Districts=c(' अमळनेर','एरंडोल','चाळीसगाव',' चोपडा ','जळगाव','जामनेर','धरणगांव','पाचोरा','पारोळा','बोदवड ','भडगाव ','भुसावळ','मुक्ताईनगर','यावल','रावेर')
Deceased_count=c(8,11,11,15,22,45,29,14,18,10,15,2,18,6,5)

#barplot(Deceased_count,
#        names.arg = District,
#        col = rainbow(length(District)),  # Add vibrant colors
#        main = "Deceased Count by District",
#        xlab = "District",
#        ylab = "Deceased Count",
#        las = 2,  # Rotate axis labels for better readability
#        cex.names = 0.8)  # Adjust label size

severity_colors <- colorRampPalette(c("yellow", "orange", "darkorange",'tomato','red1','red3','red4'))(length(Deceased_count))

par(bg='beige',col.axis='red2',col.lab='tomato2',col.main='red3')
# Bar plot with custom colors
bp4=barplot(height=Deceased_count,
        names.arg = Districts,
        col = severity_colors[rank(Deceased_count)], # Assign colors based on count
        main = "Deceased Count by District (Severity Highlighted)",
        xlab = "District",
        ylab = "Deceased Count (not in %)",
        las = 2,      # Rotate district labels for better readability
        cex.names = 0.8,  # Adjust label size
        border = "black"  # Add a black border for clarity
)
percentages=round(Deceased_count/sum(Deceased_count)*100,1)
text(bp4,Deceased_count+2,labels=paste(percentages,"%"),cex=0.8,col='black')
#mtext("Suicidal_Ideation", side = 1, line = 3, col = "red1", font = 2)  # X-axis label
#mtext("Counts", side = 2, line = 3, col = "red1", font = 2) 
grid(nx=NA,ny=NULL,col = 'black',lty=2,lwd=1.2)

```

```{r}
table(df1$bpl_status,df1$land_type)
Landt_type=c('lease','none','own')
BPL_status_YES=c(4,2,108)
BPL_status_NO=c(2,6,107)

Data=rbind(BPL_status_YES,BPL_status_YES);Data
colors=c('#843b67','tomato2')
par(bg='#E2D8A5')
barplot(Data,beside=FALSE,
        col=colors,
        legend=c('YES',"NO"),
        names.arg=Landt_type,
        main="Classification of Land type according to BPL status",
        xlab="Type of Land",
        ylab="Counts in (numbers)")
grid(nx=NA,ny=NULL,lty="dotted",col="black")

```

